In [77]:
#########################
# Introduction to numpy #
#########################

In [5]:
#import pandas as pd

In [9]:
#df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [15]:
#df.head()

In [31]:
import numpy as np

In [33]:
np

<module 'numpy' from 'C:\\Users\\ravis\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [75]:
#################
# Create Numpy #
################

In [73]:

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [47]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [65]:
a[2]

10

In [51]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6])

In [53]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [59]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [71]:
#####################################
# Creating Multi-dimentional arrays #
####################################

In [69]:
np.zeros((5, 3))# 5 rows and 3 colomns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [83]:
n = np.array([
[1,2,3],
[4,5,6],
[7,8,9]])

In [87]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
n[0]

array([1, 2, 3])

In [92]:
n[0][1]

2

In [94]:
n[0,1]

2

In [96]:
n[0][2] = 10
n

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [98]:
n[2] = [1, 1, 1]

In [100]:
n

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [102]:
n[ :, 1]

array([2, 5, 1])

In [104]:
n[ :, 2] = [ 0, 4, 5]

In [106]:
n

array([[1, 2, 0],
       [4, 5, 4],
       [1, 1, 5]])

In [113]:
#########################
# Generate random array #
#########################

In [115]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [117]:
np.random.seed(2)
100*np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [119]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [123]:
np.random.seed(2)
np.random.randint(low= 0, high= 100, size = (5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [125]:
#######################################
#      Element wise Operation         #
######################################

In [135]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [137]:
a + 1

array([1, 2, 3, 4, 5])

In [139]:
a * 2

array([0, 2, 4, 6, 8])

In [146]:
b = ( 10 +(a*2)) **2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [144]:
#####################################
#     Comparsion  Operations        #
#####################################

In [148]:
a >= 2

array([False, False,  True,  True,  True])

In [150]:
a > b

array([False, False,  True,  True,  True])

In [152]:
a[ a> b]

array([2, 3, 4])

In [ ]:
# Summerization Operation

In [154]:
a 

array([0, 1, 2, 3, 4])

In [156]:
a.min()

0

In [158]:
a.max()

4

In [160]:
a.std()

1.4142135623730951

In [162]:
a.mean()

2.0