In [ ]:
# Vector Operation

In [1]:
import numpy as np

In [3]:
u = np.array( [ 2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [5]:
 2*u

array([ 4,  8, 10, 12])

In [7]:
v = np.array([2, 0, 0, 4])
v

array([2, 0, 0, 4])

In [9]:
u + v

array([ 4,  4,  5, 10])

In [11]:
# Multiplications

In [37]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [39]:
vector_vector_multiplication(u, v)

28.0

In [35]:
v.dot(u)

28

In [ ]:
# Matrix Vector multiplication

In [113]:
U = np.array([[2, 4, 5,7],
             [5, 6, 7, 9],
             [4, 6, 9, 4]])
U

array([[2, 4, 5, 7],
       [5, 6, 7, 9],
       [4, 6, 9, 4]])

In [115]:
V = np.array([[2, 3, 4],
              [4, 5, 6],
              [7, 8, 9],
              [2, 4, 5]])
V

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9],
       [2, 4, 5]])

In [117]:
U.shape

(3, 4)

In [119]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

In [121]:
matrix_vector_multiplication(U,v)

array([32., 46., 24.])

In [123]:
U.dot(v)

array([32, 46, 24])

In [125]:
U.shape

(3, 4)

In [127]:
V.shape

(4, 3)

In [155]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_column = V.shape[1]
    

    result = np.zeros((num_rows, num_column))
    for i in range ( num_column):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[: ,i] = Uvi
    return result 
   

In [157]:
matrix_matrix_multiplication(U, V)

array([[ 69.,  94., 112.],
       [101., 137., 164.],
       [103., 130., 153.]])

In [159]:
U.dot(V)

array([[ 69,  94, 112],
       [101, 137, 164],
       [103, 130, 153]])

In [ ]:
# Identity Matrix

In [163]:
I = np.eye(3)

In [165]:
V

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9],
       [2, 4, 5]])

In [169]:
V.dot(I)

array([[2., 3., 4.],
       [4., 5., 6.],
       [7., 8., 9.],
       [2., 4., 5.]])

In [ ]:
# Matrix Inverse

In [173]:
Vs = V[[0, 1, 2]]
Vs

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 3.94064967e+15, -6.56774946e+15,  2.62709978e+15],
       [-7.88129935e+15,  1.31354989e+16, -5.25419957e+15],
       [ 3.94064967e+15, -6.56774946e+15,  2.62709978e+15]])

In [177]:
Vs_inv.dot(Vs)

array([[ 3.,  4.,  5.],
       [-7., -8., -9.],
       [ 0.,  0.,  4.]])